#database properties
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/surest-dev-db
    username: postgres
    password: Evry@123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000 # 30 seconds
      connection-timeout: 20000 # 20 seconds
      max-lifetime: 1800000 # 30 minutes
      validation-timeout: 5000 # 5 seconds

    #JPA properties
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgresSQLDialect
          show-sql: true
          format_sql: true
      hibernate:
        ddl-auto: none
        naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
      show-sql: true

    #flyway properties
    flyway:
      enabled: true
      locations: classpath:db/migration

#server port
server:
  port: 9090

#jwt properties
jwt:
  secret: my-super-secret-key-that-is-long-enough-1234567890!@#
  expiration-time: 3600000

#Swagger properties
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui